version: 0.2
env:
  variables:
    # https://github.com/cdklabs/cdk-ecr-deployment/issues/478#issuecomment-1938020710
    NO_PREBUILT_LAMBDA: "1"
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm install aws-cdk -g
      - CDK_STACK=$(aws cloudformation list-stacks --query 'StackSummaries[?(StackName==`CDKToolkit` && StackStatus==`CREATE_COMPLETE`)].StackId' --output text)
  pre_build:
    commands:
      # Recreate symlinks that are lost when GitHub source is zipped
      - rm -rf ./PetAdoptions/cdk/pet_stack/resources/microservices
      - mkdir -p ./PetAdoptions/cdk/pet_stack/resources/microservices
      - ln -s ../../../../payforadoption-go ./PetAdoptions/cdk/pet_stack/resources/microservices/payforadoption-go
      - ln -s ../../../../petadoptionshistory-py ./PetAdoptions/cdk/pet_stack/resources/microservices/petadoptionshistory-py
      - ln -s ../../../../petlistadoptions-go ./PetAdoptions/cdk/pet_stack/resources/microservices/petlistadoptions-go
      - ln -s ../../../../petsearch-java ./PetAdoptions/cdk/pet_stack/resources/microservices/petsearch-java
      - ln -s ../../../../petsite ./PetAdoptions/cdk/pet_stack/resources/microservices/petsite
      - ln -s ../../../../trafficgenerator ./PetAdoptions/cdk/pet_stack/resources/microservices/trafficgenerator
  build:
    commands:
      - cd ./PetAdoptions/cdk/pet_stack/
      - npm install
      - if [ -z "$CDK_STACK" ] ; then cdk bootstrap ; else echo "Already bootstrapped" ; fi
      - npm run build
      - cdk deploy Services --context admin_role=${EE_TEAM_ROLE_ARN} --require-approval=never --verbose -O ./out/out.json
      - cdk deploy Applications --require-approval=never --verbose -O ./out/out.json
artifacts:
  files: "./PetAdoptions/cdk/pet_stack/out/out.json"
